[package]
name = "polygon-arbitrage-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.0", features = ["abigen", "rustls"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"