polygon_rpc_url = "https://polygon-rpc.com"

[uniswap]
router_address = "0x1b02da8cb0d097eb8d57a175b88c7d8b47997506" # QuickSwap Router on Polygon

[sushiswap]
router_address = "0x1b02da8cb0d097eb8d57a175b88c7d8b47997506" # For example, same as QuickSwap here

[tokens]
weth = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
usdc = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"

[min_profit_usdc] = 1.0
trade_size_weth = 1.0